{
 "title": "Debezium PostgreSQL CDC Dashboard",
 "tags": [
  "Debezium",
  "Kafka Connect",
  "CDC",
  "PostgreSQL"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(kafka_connect_app_info, instance)"
   },
   {
    "name": "connector",
    "query": "label_values(kafka_connect_connector_info, connector)"
   }
  ]
 },
 "panels": [
  {
   "title": "Connect Worker Status",
   "type": "table",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 6 },
   "targets": [
    {
     "expr": "kafka_connect_app_info{instance=~\"$instance\"}"
    },
    {
     "expr": "sum by (instance) (kafka_connect_worker_connector_count{instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_worker_task_count{instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_worker_connector_startup_success_total{instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_worker_connector_startup_failure_total{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Connectors Details",
   "type": "table",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "kafka_connect_connector_info{instance=~\"$instance\",connector=~\"$connector\"}"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_total_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_running_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_failed_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Source Record Poll Rate",
   "type": "graph",
   "gridPos": { "x": 0, "y": 14, "w": 12, "h": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_connect_source_task_source_record_poll_total{instance=~\"$instance\",connector=~\"$connector\"}[1m])",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Write Rate",
   "type": "graph",
   "gridPos": { "x": 12, "y": 14, "w": 12, "h": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_connect_source_task_source_record_write_total{instance=~\"$instance\",connector=~\"$connector\"}[1m])",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Record Size Average",
   "type": "graph",
   "gridPos": { "x": 0, "y": 20, "w": 12, "h": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_size_avg{clientId=\"connector-producer-postgres-source-0\",instance=\"kafka-connect:9876\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Batch Size Average",
   "type": "graph",
   "gridPos": { "x": 12, "y": 20, "w": 12, "h": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connector_task_batch_size_avg{instance=\"kafka-connect:9876\",task=\"0\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Record Per Request Avg",
   "type": "graph",
   "gridPos": { "x": 0, "y": 26, "w": 12, "h": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_records_per_request_avg{clientId=\"connector-producer-postgres-source-0\",instance=\"kafka-connect:9876\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Record Send AVG",
   "type": "graph",
   "gridPos": { "x": 12, "y": 26, "w": 12, "h": 6 },
   "yaxes": [
    { "format": "item" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_topic_record_send_total{clientId=\"connector-producer-postgres-source-0\",instance=\"kafka-connect:9876\",topic=\"postgresql-jdbc-bulk-users\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  }
 ]
}